name: Test

on:
  workflow_dispatch:
    
permissions:
  contents: read
  
env:
  SETUP_CMD : ${{ vars.SETUP_CMD }}

  
jobs:

  test:
    runs-on: ubuntu-latest #24.04-arm
    environment: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: install cloudflared
      run: |
        curl -L https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-archive-keyring.gpg >/dev/null
        echo "deb [signed-by=/usr/share/keyrings/cloudflare-archive-keyring.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee  /etc/apt/sources.list.d/cloudflared.list
        sudo apt update
        sudo apt-get install cloudflared -y

    - name: setup ttyd
      run: sudo apt install ttyd -y

    - name: Setup cf
      run: |
       sudo cloudflared service install ${{ env.CF_KEY }}

        
 